/*ALTER TABLE persons
ADD emails VARCHAR(50) NOT NULL

SELECT * FROM persons*/


/*REMOVE THE COLUMN PHONE FROM YHE PERSONS TABLE */

ALTER TABLE personS
DROP COLUMN phone 

SELECT * FROM persons

