 /* OPERATOR

 => RANGE OPERATOR
 
 BETWEEN

  QUES) RETRIEVE ALL CUSTOMERS WHOSE SCORE FALLS
  IN RANGE BETWEEN 300 TO 600

   SELECT*
   FROM customers
   WHERE score BETWEEN 300 AND 600

   ALSO IT COULD BE WRITTEN AS

   SELECT*
   FROM customers
   WHERE score>=300  AND score<=600
   */