/*OPERATORS 
  => COMPARISON OPERATOR
   1) = 

   QUES) RETRIEVE ALL CUSTOMERS FROM USA

   SELECT*
   FROM customers
   WHERE country = 'USA'
   

   2)  !=
   QUES) RETRIEVE ALL  CUSTOMERS WHO ARE NOT FROM USA

   SELECT*
   FROM customers
   WHERE country!= 'USA'

   3) >

   QUES) RETRIEVE ALL  CUSTOMERS WITH A SCORE LESS THAN 500

   SELECT*
   FROM customers
   WHERE score>500


   4) >=

    QUES) RETRIEVE ALL  CUSTOMERS WITH A SCORE GREATER THAN 500 OR MORE

	SELECT*
	FROM customers
	WHERE SCORE>=500

   5) <

    QUES) RETRIEVE ALL  CUSTOMERS WITH A SCORE LESS THAN 500

	SELECT*
	FROM customers
	WHERE score<500 */