/* OPERATOR
  => LOGICAL OPERATORS

  1) AND - ALL CONDITIONS MUST BE TRUE

  QUES) RETRIEVE ALL THE CUSTOMERS WHO ARE FROM THE USA
         AND HAVE A SCORE GREATER THAN 500

		 SELECT*
		 FROM customers
		 WHERE country = 'USA' AND  score >500

  2) OR - ATLEAST 1 CONDITION SHOULD BE TRUE

  QUES)RETRIEVE ALL THE CUSTOMERS WHO ARE EITHER FROM THE USA
         OR HAVE A SCORE GREATER THAN 500 

		  SELECT*
		 FROM customers
		 WHERE country = 'USA' OR  score >500 

  3) NOT- (REVERSE ) EXCLUDES MATCHING VALUES

   QUES)RETRIEVE ALL THE CUSTOMERS WITH A SCORE NOT LESS THAN 500
       
	   SELECT*
	   FROM customers
	   WHERE NOT score < 500*/


